### ISSUE TITLE
Config Errored files

### ISSUE THREAD

**Issue by gmnovakrc** [MJaroslav/TrainDieselFix#1]
MC 1.7.10
Forge 10.13.4.1614
Train Diesel Fix 1.1.0
Traincraft-4.4.1_CE_4

These cnfg error files sporadically popup when I'm playing, making/testing a modpack. 
They are an exact copy of the regular config file when opened, nothing changed compared to actual cnfg file, just the name.
Haven't been using/interacting with any items from this mod or TC either.

![Screenshot (501)](https://user-images.githubusercontent.com/74471865/172692939-1df0ca56-7f38-40c4-b15f-7138cbcb1f08.png)

**Comment by MJaroslav** [comment]
You put last version of mod or updated from previous? If second variant then have you tried to remove all configs of my mod? Can you show one of it and config with common name anyway? Maybe you have some logs with it?

**Comment by gmnovakrc** [comment]
This was updated from previous version, but I will always delete every instance of the previous version of the mod, jar and cnfg file. I don't have the cnfg file saved in my modpack upload folder either, so when you download and play, it creates a brand new cnfg file. I will always delete and then re-download the pack whenever I update the pack, so its always a fresh start.

I just compared every single cnfg to the original and they're all exactly the same.
But I did just find the error in the latest log report, I did CTRL+F "traindie" and it was the 3rd highlight.

[2022-06-08-4.log.gz](https://github.com/MJaroslav/TrainDieselFix/files/8865567/2022-06-08-4.log.gz)
Its a regular zip file.

**Comment by MJaroslav** [comment]
In logs: `java.lang.RuntimeException: Unknown character '(' in 'P:/Technic/.technic/modpacks/nerdherd-craft/config/traindieselfix.cfg:5'`

Show me any errored file anyway.

**Comment by gmnovakrc** [comment]
Cnfgs and latest log file.

[Traindieselfix cnfg.zip](https://github.com/MJaroslav/TrainDieselFix/files/8868903/Traindieselfix.cnfg.zip)

[latest.zip](https://github.com/MJaroslav/TrainDieselFix/files/8868915/latest.zip)

**Comment by MJaroslav** [comment]
I found an error, I used quotes in the config field name. I will correct it during the day along with making additional changes.

**Comment by MJaroslav** [comment]
Fixed (v1.1.1).
